#ifndef SETTINGS
#define SETTINGS

#define RESOURCE_PATH "X:/C/Rhapsodia/resources/"

#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 720

#define CHUNKS_COUNT_X 3
#define CHUNKS_COUNT_Y 2
#define CHUNKS_COUNT_Z 3

#define CHUNKS_COUNT CHUNKS_COUNT_X * CHUNKS_COUNT_Y * CHUNKS_COUNT_Z

#define CHUNK_SIZE 16

#define INTERACT_DISTANCE 5

#define MOUSE_SENSITIVITY 0.003f

#endif /* SETTINGS */
